name: Continuous Integration
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

jobs:
  python-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: format
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: black --all-files
  python-flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: flake8 --all-files
  python-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: isort
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: isort --all-files
  python-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: mypy
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: mypy --all-files
  lint-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: requirements-txt-fixer --all-files
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: markdownlint-cli2 --all-files
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: yamllint --all-files
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: check-json --all-files
  lint-shell-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: shellcheck --all-files
  lint-trailing-whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: trailing-whitespace --all-files
  lint-eof-newline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: end-of-file-fixer --all-files
